package com.musicmanager.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * La classe DatabaseManager gestisce le connessioni al database e inizializza
 * automaticamente la struttura del database all'avvio dell'applicazione,
 * creando le tabelle necessarie se non già presenti.
 */

public class DatabaseManager {

    private static final String URL = "jdbc:h2:./data/music_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";

    /**
     * URL di connessione al database H2 embedded.
     * 
     * - ./data/music_db   : database salvato localmente in un file nella cartella "data"
     * - MODE=PostgreSQL   : abilita la compatibilità sintattica con PostgreSQL
     * - DB_CLOSE_DELAY=-1 : mantiene il database disponibile fino alla chiusura dell'applicazione
     */

    private static final String USER = "sa";
    private static final String PASSWORD = "";

    // Il metodo getConnection() restituisce una connessione attiva al database H2.

    public static Connection getConnection() throws SQLException {
        return DriverManager.getConnection(URL, USER, PASSWORD);
    }

    /**
     * Il metodo initializeDatabase() apre una connessione al database ed esegue le operazioni di inizializzazione
     * (creazione delle tabelle necessarie se non esistono già), gestendo automaticamente la chiusura delle risorse
     * e gli eventuali errori SQL.
     */

    public static void initializeDatabase() {

        String createTrackTable = "CREATE TABLE IF NOT EXISTS Tracks (" +
                "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "title VARCHAR(255) NOT NULL, " +
                "author VARCHAR(255) NOT NULL, " +
                "length INT NOT NULL, " + // durata del brano espressa in secondi
                "genre VARCHAR(100), " +
                "\"year\" INT" +
                ");";

        try (Connection conn = getConnection(); Statement stmt = conn.createStatement()) {
            stmt.execute(createTrackTable);
            System.out.println("[H2 DATABASE] Init completata.");
        } catch (SQLException e) {
            System.err.println("[H2 DATABASE ERROR] Init non riuscita: " + e.getMessage());
        }

    }
    
}