package com.musicmanager.database;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Classe responsabile della connessione al database H2.
 *
 * Scelta architetturale - Singleton Pattern:
 * Garantisce una singola istanza e una singola connessione al database durante l’esecuzione dell’applicazione.
 */

public class DatabaseManager {

    /**
     * Configurazione del database H2 embedded.
     * Garantisce la compatibilità con PostgreSQL e la persistenza dei dati nella cartella locale "data" fino alla chiusura dell'applicazione.
     */

    private static final String URL = "jdbc:h2:./data/music_db;MODE=PostgreSQL;DB_CLOSE_DELAY=-1";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private static DatabaseManager instance;
    private Connection connection;

    /**
     * Costruttore privato del Singleton.
     * Impedisce l’istanziazione diretta della classe e inizializza il database.
     */

    private DatabaseManager() {
        initializeDatabase(); 
    }

    /**
     * Restituisce l’istanza di DatabaseManager, creandola se necessario.
     */

    public static synchronized DatabaseManager getInstance() {
        if (instance == null) {
            instance = new DatabaseManager();
        }
        return instance;
    }

    /**
     * Restituisce la connessione al database H2, creandola se necessario.
     */

    public Connection getConnection() throws SQLException {
        if (connection == null || connection.isClosed()) {
            connection = DriverManager.getConnection(URL, USER, PASSWORD);
        }
        return connection;
    }

    /**
     * Chiude la connessione al database.
     */

    public void closeConnection() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
                System.out.println("[H2 DATABASE] INFO: Database connection closed successfully.");
            }
        } catch (SQLException e) {
            System.err.println("[H2 DATABASE] ERROR: Database connection closure failed: " + e.getMessage());
        }
    }

    /**
     * Inizializza il database creando le tabelle necessarie se non esistono.
     */

    private void initializeDatabase() {

        String tracks = "CREATE TABLE IF NOT EXISTS Tracks (" +
                        "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                        "title VARCHAR(255) NOT NULL, " +
                        "author VARCHAR(255) NOT NULL, " +
                        "length INT NOT NULL, " +
                        "genre VARCHAR(100), " +
                        "\"year\" INT, " +
                        "playCount INT" +
                        ");";

        String playlists =
            "CREATE TABLE IF NOT EXISTS Playlists (" +
            "id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
            "name VARCHAR(255) NOT NULL UNIQUE" +
            ");";

        String playlistTracks =
                "CREATE TABLE IF NOT EXISTS Playlist_Tracks (" +
                "playlist_id INT NOT NULL, " +
                "track_id INT NOT NULL, " +
                "PRIMARY KEY (playlist_id, track_id), " +
                "FOREIGN KEY (playlist_id) REFERENCES Playlists(id) ON DELETE CASCADE, " +
                "FOREIGN KEY (track_id) REFERENCES Tracks(id) ON DELETE CASCADE" +
                ");";                

        try {
            Connection conn = getConnection();
            try (Statement stmt = conn.createStatement()) {
                stmt.execute(tracks);
                stmt.execute(playlists);      
                stmt.execute(playlistTracks); 
                System.out.println("[H2 DATABASE] INFO: Database initialized successfully.");
            }
        } catch (SQLException e) {
            System.err.println("[H2 DATABASE] ERROR: Database initialization failed: " + e.getMessage());
        }

    }

}